import { Issue } from '../app/interfaces';

export const issues: Issue[] = [
  {
    issueNo: 101,
    title: 'Login button not working',
    description:
      'The login button fails to redirect the user to the dashboard.',
    priority: 'high',
    type: 'Malfunction',
    completed: new Date('2024-12-01'),
  },
  {
    issueNo: 102,
    title: 'Add search functionality',
    description:
      'Implement a search bar on the homepage to allow users to search for products.',
    priority: 'low',
    type: 'Function',
    completed: null,
  },
  {
    issueNo: 103,
    title: 'Update API documentation',
    description:
      'Revise the API documentation to include the newly added endpoints.',
    priority: 'low',
    type: 'Documentation',
    completed: new Date('2024-11-28'),
  },
  {
    issueNo: 104,
    title: 'Fix image upload bug',
    description: 'Image upload functionality fails for files larger than 5MB.',
    priority: 'high',
    type: 'Malfunction',
  },
  {
    issueNo: 105,
    title: 'Implement dark mode',
    description: 'Add a dark mode feature to the user settings.',
    priority: 'low',
    type: 'Function',
    completed: new Date('2024-12-05'),
  },
  {
    issueNo: 106,
    title: 'Broken link on About page',
    description: "The 'Contact Us' link on the About page is broken.",
    priority: 'high',
    type: 'Malfunction',
  },
  {
    issueNo: 107,
    title: 'Add user login functionality',
    description: 'Implement a user login page with authentication.',
    priority: 'high',
    type: 'Function',
    completed: null,
  },
  {
    issueNo: 108,
    title: 'Fix dashboard loading bug',
    description:
      'Resolve the issue where the dashboard takes too long to load.',
    priority: 'high',
    type: 'Malfunction',
    completed: null,
  },
  {
    issueNo: 109,
    title: 'Update API documentation',
    description: 'Add new API endpoints to the documentation.',
    priority: 'low',
    type: 'Documentation',
    completed: new Date('2023-12-01'),
  },
  {
    issueNo: 110,
    title: 'Optimize database queries',
    description: 'Improve performance by optimizing slow database queries.',
    priority: 'high',
    type: 'Function',
    completed: null,
  },
  {
    issueNo: 111,
    title: 'Correct typos in user guide',
    description: 'Fix typos in the user guide section on settings.',
    priority: 'low',
    type: 'Documentation',
    completed: new Date('2023-11-28'),
  },
  {
    issueNo: 112,
    title: 'Investigate login timeout issue',
    description:
      'Users are experiencing timeouts when logging in during peak hours.',
    priority: 'high',
    type: 'Malfunction',
    completed: null,
  },
  {
    issueNo: 113,
    title: 'Implement dark mode feature',
    description: 'Add a dark mode option for the application interface.',
    priority: 'low',
    type: 'Function',
    completed: null,
  },
  {
    issueNo: 114,
    title: 'Fix search results pagination',
    description: 'Pagination on search results is not functioning correctly.',
    priority: 'high',
    type: 'Malfunction',
    completed: null,
  },
  {
    issueNo: 115,
    title: 'Add examples to API usage guide',
    description: 'Include code examples in the API usage documentation.',
    priority: 'low',
    type: 'Documentation',
    completed: new Date('2023-12-05'),
  },
  {
    issueNo: 116,
    title: 'Resolve crash on report generation',
    description: 'The application crashes when generating large reports.',
    priority: 'high',
    type: 'Malfunction',
    completed: null,
  },
  {
    issueNo: 117,
    title: 'Improve mobile responsiveness',
    description: 'Ensure the application works seamlessly on mobile devices.',
    priority: 'high',
    type: 'Function',
    completed: null,
  },
  {
    issueNo: 118,
    title: 'Add tooltips to settings menu',
    description:
      'Provide explanatory tooltips for options in the settings menu.',
    priority: 'low',
    type: 'Function',
    completed: null,
  },
  {
    issueNo: 119,
    title: 'Fix broken links in footer',
    description: 'Some links in the footer redirect to incorrect pages.',
    priority: 'high',
    type: 'Malfunction',
    completed: null,
  },
  {
    issueNo: 120,
    title: 'Add localization support',
    description: 'Implement multi-language support for the application.',
    priority: 'high',
    type: 'Function',
    completed: null,
  },
  {
    issueNo: 121,
    title: 'Document environment setup',
    description:
      'Provide a detailed guide for setting up the development environment.',
    priority: 'low',
    type: 'Documentation',
    completed: new Date('2023-12-06'),
  },
  {
    issueNo: 122,
    title: 'Fix issue with file uploads',
    description: 'File uploads fail intermittently for large files.',
    priority: 'high',
    type: 'Malfunction',
    completed: null,
  },
  {
    issueNo: 123,
    title: 'Enhance search functionality',
    description:
      'Add advanced filters and sorting options to the search feature.',
    priority: 'low',
    type: 'Function',
    completed: null,
  },
  {
    issueNo: 124,
    title: 'Resolve UI glitch in profile settings',
    description:
      'UI elements in profile settings are misaligned on certain resolutions.',
    priority: 'high',
    type: 'Malfunction',
    completed: null,
  },
];
